### ISSUE TITLE
Test fail

### ISSUE THREAD

**Issue by ScoreUnder** [thoughtbot/pick#116]
Compiling from e79f95bbd208c580ea424848f64b34fb1ded10c4.
When running `make check`, the first test fails and the rest don't get tested.

test-suite.log:
```
==================================
   pick 1.3.0: ./test-suite.log
==================================

# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: tests/test.sh
===================

./tests/01.in: wrong exit code
test: read: Input/output error
FAIL tests/test.sh (exit status: 1)

```

Pick itself works fine, from what I can tell.

----

For the record, I've checked this against a fresh install of Arch under docker (pritunl/archlinux), and I get the same result.

**Comment by mptre** [comment]
Could you try applying the following patch[1] locally and see if the
problem still remains?

[1] https://github.com/thoughtbot/pick/pull/113

**Comment by ScoreUnder** [comment]
After applying the patch, `make check` still fails with the same error, but this time on test 03.

`git diff` after applying the patch:
```diff
diff --git a/tests/test.sh b/tests/test.sh
index 3de583a..0b13640 100755
--- a/tests/test.sh
+++ b/tests/test.sh
@@ -2,8 +2,8 @@
 
 field() {
   awk '
-  /^'$1':/ { sub(/^[^:]+: */, ""); print; exit 0 }
-  END { exit 1 }'
+  /^'$1':/ { sub(/^[^:]+: */, ""); print; found=1 }
+  END { exit !found }'
 }
 
 input() {
```

**Comment by mptre** [comment]
What if you apply the following patch:

```diff
diff --git tests/test.c tests/test.c
index 2402e5c..33b4291 100644
--- tests/test.c
+++ tests/test.c
@@ -70,7 +70,7 @@ parseinput(const char *s)
 				return;
 			switch (*s) {
 			case 'b':
-				c = 0x08;
+				c = 0x7F;
 				break;
 			case 'e':
 				c = 0x1B;
```

**Comment by ScoreUnder** [comment]
That gets it a lot farther. It now fails on test 8. 

It's the same error code as before:

```
./tests/08.in: wrong exit code
test: read: Input/output error
FAIL tests/test.sh (exit status: 1)
```

**Comment by mptre** [comment]
On Thu, May 05, 2016 at 10:42:10AM -0700, Score_Under wrote:
> That gets it a lot farther. It now fails on test 8. 
> 
> It's the same error code as before:
> 
> ```
> ./tests/08.in: wrong exit code
> test: read: Input/output error
> FAIL tests/test.sh (exit status: 1)
> ```

Unfortunately I'm out of ideas now. Could you provide more data: OS,
compiler (including version), sh (including version). Thanks.

**Comment by ScoreUnder** [comment]
`Linux kirisame 4.3.3.201601051958-1-grsec #1 SMP PREEMPT Tue Jan 19 03:00:34 GMT 2016 x86_64 GNU/Linux`

**Comment by mike-burns** [comment]
It's not dash but it might be Linux.

```
~/pick% make check ; cat test-suite.log
make  tests/test
make[1]: Entering directory '/home/mike/pick'
make[1]: 'tests/test' is up to date.
make[1]: Leaving directory '/home/mike/pick'
make  check-TESTS
make[1]: Entering directory '/home/mike/pick'
make[2]: Entering directory '/home/mike/pick'
FAIL: tests/test.sh
make[3]: Entering directory '/home/mike/pick'
make  all-am
make[4]: Entering directory '/home/mike/pick'
make[4]: Leaving directory '/home/mike/pick'
make[3]: Leaving directory '/home/mike/pick'
============================================================================
Testsuite summary for pick 1.3.0
============================================================================
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See ./test-suite.log
Please report to hello@thoughtbot.com
============================================================================
Makefile:777: recipe for target 'test-suite.log' failed
make[2]: *** [test-suite.log] Error 1
make[2]: Leaving directory '/home/mike/pick'
Makefile:883: recipe for target 'check-TESTS' failed
make[1]: *** [check-TESTS] Error 2
make[1]: Leaving directory '/home/mike/pick'
Makefile:1089: recipe for target 'check-am' failed
make: *** [check-am] Error 2
==================================
   pick 1.3.0: ./test-suite.log
==================================

# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: tests/test.sh
===================

./tests/02.in: wrong exit code
test: read: Input/output error
```

It has nothing to do with the test script:

```
~/pick% tests/test -i '^N^N^N^N^M' -- < tests/02.in
1
test: read: Input/output error
```

However with this diff:

```diff
diff --git a/tests/test.c b/tests/test.c
index 2402e5c..1cf6b84 100644
--- a/tests/test.c
+++ b/tests/test.c
@@ -152,6 +152,8 @@ parent(int master, int slave)
                                continue;
                }
 
+               sleep(1);
+
                /* Read and discard output from child process, necessary since
                 * it flushes. */
                if (read(master, buf, sizeof(buf)) < 0)
```

I get:

```
~/pick% tests/test -i '^N^N^N^N^M' -- < tests/02.in
1
```

Calle had me try `sleep(0.5);` and `sleep(0.75);`, but neither worked.

**Comment by ScoreUnder** [comment]
>Calle had me try `sleep(0.5);` and `sleep(0.75);`, but neither worked.

`sleep` takes integer arguments, so you will need to use `usleep` (microsecond sleep) instead. With `usleep(1000)` (or higher), the test suite reliably fails on test 12 on my machine, which is the farthest it has ever got. I poked around further and noticed I get the same result if I just ignore EIO:

```diff
diff --git a/tests/test.c b/tests/test.c
index 2402e5c..9babb78 100644
--- a/tests/test.c
+++ b/tests/test.c
@@ -155,7 +155,8 @@ parent(int master, int slave)
                /* Read and discard output from child process, necessary since
                 * it flushes. */
                if (read(master, buf, sizeof(buf)) < 0)
-                       err(1, "read");
+                       if (errno != EIO)
+                               err(1, "read");
        }
 }
 
```

A little looking around later, I found this: https://stackoverflow.com/questions/2975733/reading-from-a-pty

And I came up with this patch instead:

```diff
diff --git a/tests/test.c b/tests/test.c
index 2402e5c..d24bf7b 100644
--- a/tests/test.c
+++ b/tests/test.c
@@ -128,8 +128,6 @@ parent(int master, int slave)
        struct timeval timeout;
        fd_set rfd;
 
-       close(slave);
-
        if (write(master, input.v, input.nmemb) < 0)
                err(1, "write");
 
@@ -157,6 +155,12 @@ parent(int master, int slave)
                if (read(master, buf, sizeof(buf)) < 0)
                        err(1, "read");
        }
+
+       // If the last slave file descriptor closes while a 'read' call is in
+       // progress, the read may fail with EIO. To avoid that happening in
+       // the above loop, this copy of the slave file descriptor is left open
+       // until now.
+       close(slave);
 }
 
 void
```

This exhibits the same behaviour as with a "long enough" sleep: tests pass up to test 12, which fails.

```
./tests/12.in: wrong exit code
test: time limit exceeded
FAIL tests/test.sh (exit status: 1)
```


I directed the info gained from the reads on the `master` fd into a file, and played it back with `pv -L 50 -q output; echo`. It looks like the å character was never deleted. I can't figure out why this happens, because it works fine interactively even when pasting the entire input at once.

**Comment by mptre** [comment]
First of: thank you all for putting the time and effort into debugging
this issue.

After some initial printf-debugging it looked like the `^D` character
was not sent as is to the pick process. Running strace(1) revealed some
interesting output (irrelevant output stripped out):

```
$ printf 'xx\nxå\n' | strace -f -e trace=read,write ./tests/test -i 'xå^B^D\n'
11548 write(3, "x\303\245\2\4\n", 6)    = 6
11549 read(3, "x\303\245\2\0\n", 4096)  = 6
```

Notice how `\4` got turned into `\0` which implies that some input
processing is taking place. Looking up the character `0x04` in ascii(1)
shows that it is equivalent to the `eot` character. Pressing `^D` while
reading input usually terminates the current process. This done is when
canonical mode is enabled and presence of the `^D` character in the
input stream will be intercepted as sending a terminating signal to the
process. However I found this interesting since pick disables canonical
mode in order to receive input as is. So this must be a timing issue:
the `tests/test.c` command sends its input prior the call to
tcsetattr(3) in pick. To get around this issue we could use the
following heuristic: when pick flushes its output we can be sure that
the tcsetattr(3) call has been made. The solution is therefor to
postpone the call to write(2) after the file descriptor is ready for
reading.

```diff
diff --git a/tests/test.c b/tests/test.c
index 2402e5c..48350ed 100644
--- a/tests/test.c
+++ b/tests/test.c
@@ -15,6 +15,7 @@ static int gotsig;
 
 static struct {
 	size_t nmemb;
+	size_t written;
 	char v[128];
 } input;
 
@@ -126,13 +127,9 @@ parent(int master, int slave)
 {
 	char buf[BUFSIZ];
 	struct timeval timeout;
+	ssize_t n;
 	fd_set rfd;
 
-	close(slave);
-
-	if (write(master, input.v, input.nmemb) < 0)
-		err(1, "write");
-
 	memset(&timeout, 0, sizeof(timeout));
 	timeout.tv_sec = 1;
 	while (!gotsig) {
@@ -156,7 +153,16 @@ parent(int master, int slave)
 		 * it flushes. */
 		if (read(master, buf, sizeof(buf)) < 0)
 			err(1, "read");
+		if (input.written < input.nmemb) {
+			if ((n = write(master, input.v + input.written,
+					    input.nmemb - input.written)) == -1)
+				err(1, "write");
+			else
+				input.written += n;
+		}
 	}
+
+	close(slave);
 }
 
 void
```

How to move forward: @ScoreUnder should definitely be credit in the Git
history by creating a new PR with the move of the close call. Remember
to replace the usage of C99 style comments. I could then commit the
change above. Sounds good?

**Comment by ScoreUnder** [comment]
I've put in a PR referencing this issue (to move the `close` call).

Testing with the changes you've given in your comment above, all tests pass for me. Thanks for guiding me through this.

**Comment by calleerlandsson** [comment]
Great work everyone! Thanks for collaborating to fix this.

I have merged @ScoreUnder's PR and am ready to merge a PR from @mptre with the remaining changes.

**Comment by calleerlandsson** [comment]
Now that #118 and #119 are both merged, does `make check` pass you @ScoreUnder?

**Comment by ScoreUnder** [comment]
Yep - all tests pass. Thanks

**Comment by calleerlandsson** [comment]
Awesome! Thanks for collaborating on resolving this.
