### ISSUE TITLE
AUR 404

### ISSUE THREAD

**Issue by camoy** [thoughtbot/pick#117]
The link for the AUR tarball `https://aur.archlinux.org/packages/pi/pick/pick.tar.gz` gives a 404.

**Comment by calleerlandsson** [comment]
Hey @camoy, thanks for reporting this.

The AUR installation instructions need to be updated in accordance to https://wiki.archlinux.org/index.php/Arch_User_Repository#Installing_packages for installing this package: https://aur.archlinux.org/packages/pick/

If you'd like to work on this please feel free to do so. If not, I'll get to it as soon as I have time.
