### ISSUE TITLE
`pick -o`  does not append to the output file

### ISSUE THREAD

**Issue by TwistingTwists** [thoughtbot/pick#121]
How can I use it to append to the output file?

I am using 

`pick  history | grep ffmpeg | pick -o > this.txt` - this always creates a new file. Can there be an argument which appends to the end of `this.txt`?

**Comment by mptre** [comment]
Use `>>` rather than `>` if you want to append the selected line to the
file:

```
history | pick >>file.txt
```

... or if you want to both append and write the selected line to stdout:

```
history | pick | tee -a file.txt
```

**Comment by TwistingTwists** [comment]
thanks. It solved. :)
