### ISSUE TITLE
Visual regression in 1.4

### ISSUE THREAD

**Issue by teoljungberg** [thoughtbot/pick#131]
While using `pick` under `tmux` - the screen flickers while traversing the results.

![out](https://cloud.githubusercontent.com/assets/810650/15958320/2a294506-2ef5-11e6-8653-2efdd7445fd6.gif)

I'm running pick 1.4.0 and tmux 2.1.

**Comment by calleerlandsson** [comment]
Hey @teoljungberg, thanks for reporting! Could you try building and testing if you get the same behavior at these three commits?

72239f02877034ef1b9ff35ac83f67bf4c0a3a2f
03cb04700b5e95a7714b5e12aeace55f93b9e024
2cc576ecee9242d3368bcbe9f7617ebf23f0b7b5

**Comment by teoljungberg** [comment]
72239f0 - not working as intended.
03cb047 - working as intended.
2cc576e - working as intended.

**Comment by calleerlandsson** [comment]
@teoljungberg Thanks for trying the commits out. It's seems like 72239f0 is where this was introduced. Could you try the code in #132?

**Comment by teoljungberg** [comment]
Thanks for being so quick about this - I tested out #132 and it works as intended for me.

**Comment by calleerlandsson** [comment]
Woho! 🎉

**Comment by calleerlandsson** [comment]
Closing this since #133 is now merged.
