### ISSUE TITLE
Choices are limited to one screen

### ISSUE THREAD

**Issue by dstd** [thoughtbot/pick#138]
Am I doing something wrong, or it's a limitation of `pick` – it shows only one screen of options.
So that the only way to select the items that didn't fit into the screen is to adjust the query?

// mac, homebrew, pick 1.4.0

**Comment by kylebebak** [comment]
Same for me, OSX, pick 1.3.0

Being able to scroll through more than one page of results would be fantastic

**Comment by mptre** [comment]
I've been missing this feature as well. I'm planning on trying to
implement this soon.

**Comment by calleerlandsson** [comment]
Thanks for the feedback, everyone! I also think this would be a great addition.

**Comment by mptre** [comment]
#144 has now been merged into the master branch and therefore assume this issue can be closed?

**Comment by calleerlandsson** [comment]
Definitely. Thanks, @mptre!
