### ISSUE TITLE
configure file missing in the install

### ISSUE THREAD

**Issue by justrajdeep** [thoughtbot/pick#140]
Hi 

I was trying to install from source. 

`2. Configure the distribution.

        ./configure`

But there is no configure file present in the directory.

**Comment by mptre** [comment]
If you downloaded the source code, you need to run `autogen.sh` first[1].

[1] https://github.com/thoughtbot/pick/blob/master/DEVELOPING.md#setup

**Comment by calleerlandsson** [comment]
Hey, @justrajdeep, thanks for the feedback!

Did you clone the repo or did you download the tarball?

As indicated in step one of the installation instructions, later steps assume you're installing from one of the release tarballs. Just double-checking, the latest tarball does have the `configure` file:

```sh
tar -ztf pick-1.4.0.tar.gz | grep configure
pick-1.4.0/configure
pick-1.4.0/configure.ac
```

If you cloned the repo you should follow the instructions @mptre linked to.

**Comment by calleerlandsson** [comment]
I'll close this issue due to inactivity.
