### ISSUE TITLE
Keycode sent by arrow keys in vim changes after using pick

### ISSUE THREAD

**Issue by ggilder** [thoughtbot/pick#18]
Below is the result of entering the key codes by hitting `^V` and each arrow key (up, down, right, left) in vim.

```
fresh vim startup, before running pick:
^[0A^[0B^[0C^[0D

after running pick and exiting either successfully or via interrupt:
^[[A^[[B^[[C^[[D
```

This messes up any vim mappings set for the arrow keys.

**Comment by teoljungberg** [comment]
This happens to me aswell, I compiled `pick` from the `ks-bsd` branch.

**Comment by calleerlandsson** [comment]
I think this is caused by #4.
