### ISSUE TITLE
Support for Unicode characters.

### ISSUE THREAD

**Issue by calleerlandsson** [thoughtbot/pick#2]
This should be possible using `wchar_t` arrays for storing strings instead of `char` arrays and by linking against `ncursesw` instead of `ncurses`.

**Comment by calleerlandsson** [comment]
Since we are no longer using `ncurses` we would have to do this by hand. Here is a good resource on how to read UTF-8 characters:

http://zaemis.blogspot.se/2011/06/reading-unicode-utf-8-by-hand-in-c.html

**Comment by mptre** [comment]
Closed by 03cb04700b5e95a7714b5e12aeace55f93b9e024?

**Comment by calleerlandsson** [comment]
Most definitely! Thanks for your hard work, @mptre!
