### ISSUE TITLE
No indication of cursor in pick's text entry

### ISSUE THREAD

**Issue by ggilder** [thoughtbot/pick#20]
When entering text in pick, one can use the left/right arrow keys to insert and delete characters in the middle of the entry. However, there's no visual indication of the cursor, so it's very difficult to do this accurately. :wink:

**Comment by calleerlandsson** [comment]
Thanks for reporting @ggilder. I'm able to reproduce this when calling `pick` using `system()` from within Vim. When executing `:!pick` in Vim and when I run `pick` from my shell I do get a cursor, though. Could you confirm that this is the case for you too?

**Comment by ggilder** [comment]
Yup, I get a cursor in the shell. Weird!

**Comment by calleerlandsson** [comment]
Thanks @ggilder. I think this is related to #19, #18, and #4.
