### ISSUE TITLE
Highlight matched portion of items

### ISSUE THREAD

**Issue by ggilder** [thoughtbot/pick#21]
Other fuzzy finders like [ctrlp](https://github.com/kien/ctrlp.vim) and [fzf](https://github.com/junegunn/fzf) highlight the matched portion of items, i.e. if I have an item `README.md` in the input list and my search is `mm`, the substring `ME.m` will be highlighted in a different color. This can be useful visual feedback when searching large numbers of entries, to see why a particular search is matching something unexpected.

**Comment by calleerlandsson** [comment]
I would also like this. PR's are welcome.

**Comment by Keithbsmiley** [comment]
WIP on https://github.com/thoughtbot/pick/tree/ks-underline

**Comment by Keithbsmiley** [comment]
Works, just needs to be cleaned up.

**Comment by Keithbsmiley** [comment]
See https://github.com/thoughtbot/pick/pull/24

**Comment by calleerlandsson** [comment]
This feature was added by @mptre in #97. Thanks!
