### ISSUE TITLE
Homebrew recipe?

### ISSUE THREAD

**Issue by graysonwright** [thoughtbot/pick#27]
What do you think about adding a homebrew recipe for easy installation on OS X? I'd imagine it would go a long way towards attracting new users.

**Comment by teoljungberg** [comment]
I can gladly write one once @calleerlandsson feels it's ready to get shown to the world

**Comment by Keithbsmiley** [comment]
+1 I'd be glad to help to. Should be pretty easy.

**Comment by Keithbsmiley** [comment]
I think we are holding off on this until all the cursor and screen issues are fixed.

**Comment by calleerlandsson** [comment]
That's great! Yes, I think fixing and merging #26 before publishing would be good.

**Comment by calleerlandsson** [comment]
@teoljungberg @Keithbsmiley #26 is merged and I think we are ready to package pick.

**Comment by gabebw** [comment]
We should add it to https://github.com/thoughtbot/homebrew-formulae
