### ISSUE TITLE
Running pick using system() in Vim hinders Vim from restoring the terminal on exit.

### ISSUE THREAD

**Issue by calleerlandsson** [thoughtbot/pick#4]
When I run `pick` from within Vim using the code below, when exiting Vim, the terminal state is not restored. Instead, the screen Vim drew is still visible. 

```
function! PickCommand(choices_command, pick_args, vim_command)
  try
    let selection = system(a:choices_command . " | pick " . a:pick_args)
  catch /Vim:Interrupt/
    redraw!
    return
  endtry
  redraw!
  exec a:vim_command . " " . selection
endfunction

nnoremap <leader>p :call PickCommand("find * -type f", "", ":e")<cr>
```

It would be great if someone else could replicate this. I don't know if this is a bug in pick, Vim or my terminal emulator.

... It's probably in pick.

**Comment by teoljungberg** [comment]
An idea that @calleerlandsson and I talked about IRL is to explicitly reset the terminal when closing ncurses. Right now we configuring ncurses on boot: https://github.com/thoughtbot/pick/blob/0c03b0d76a8546016f824f7f977593fcbf1dab90/src/ui.c#L46-L65
Maybe doing the same on when we're stopping ncursise might do the trick?

**Comment by ggilder** [comment]
This is actually still happening for me... do you think there are any changes to the vim function needed? Here's what I'm using:

```
" pick
function! EscapeFilePath(path)
  return substitute(a:path, ' ', '\\ ', 'g')
endfunction

function! Pick(choice_command, vim_command)
  try
    let selection = system(a:choice_command . " | pick")
  catch /Vim:Interrupt/
    " Swallow the ^C so that the redraw below happens; otherwise there will be
    " UI leftovers on the screen
    redraw!
    return
  endtry
  redraw!
  if strlen(selection) > 0
    exec a:vim_command . " " . EscapeFilePath(selection)
  endif
endfunction

nnoremap <leader>t :call Pick("find * -type f", ":e")<cr>
```

**Comment by Keithbsmiley** [comment]
@ggilder see https://github.com/thoughtbot/pick/issues/32 you need to use `pick -X`
