### ISSUE TITLE
Documentation on color codes for highlighting?

### ISSUE THREAD

**Issue by geoffharcourt** [thoughtbot/pick#44]
The highlighting of the selected match isn't visible under tmux with several colorschemes I have tried. I am having this issue using the base Thoughtbot tmux configuration with no customizations. The issue happens both in and outside of Vim. Everything works fine if I'm not in tmux.

I have a feeling there's an easy way to fix the color profiles (it works in Solarized Dark, but not in Jellybeans), but after fiddling with the colors in my profiles I'm still having trouble figuring out what attribute I should change to enable the highlighting.

**Comment by Mange** [comment]
What is your `$TERM` inside tmux?

```
> echo $TERM
```

**Comment by geoffharcourt** [comment]
.HI @mange, my $TERM in tmux is `screen-256color`

**Comment by calleerlandsson** [comment]
Thanks for reporting this @geoffharcourt.

pick is not using a specific color but instead uses the built in standout feature of the terminal.

If you run `less < /dev/null`, `(END)` should be printed at the top left of your terminal, when you press <kbd>q</kbd> it should go away. `less` should print `(END)` using the same standout feature pick uses. Can you check if you see experience similar problems with this command using different themes?

**Comment by geoffharcourt** [comment]
@calleerlandsson, when I run that in the Jellybeans theme, I see don't see any highlighting.

This could be a problem with the theme, which certainly shouldn't be a concern of this project. I'm currently able to get highlighting with fzf, so I think that project must use a different means of applying a highlight.

**Comment by calleerlandsson** [comment]
@geoffharcourt Looking at [the fzf implementation](https://github.com/junegunn/fzf/blob/master/src/curses/curses.go), they seem to explicitly set a color pair of the output whereas pick will use the terminal default standout color pair. If the less command does not give you the right color, I unfortunately think there might be a problem with your theme.

**Comment by geoffharcourt** [comment]
Thanks for the help, (I have zero experience reading C), looks like it's time to move on to a better theme.
