### ISSUE TITLE
Typed characters are not read when given a big list of choices and typing fast

### ISSUE THREAD

**Issue by calebthompson** [thoughtbot/pick#45]
Gary Bernhardt was good enough to mention this.

https://twitter.com/garybernhardt/status/575379182684766208

I've not looked into the code, but a possible solution could be a short wait before filtering after a character is typed while you look for more characters, sort of like a buffered filter? Also, threads.

**Comment by mike-burns** [comment]
Can anyone repro this yet?

**Comment by calleerlandsson** [comment]
I can reproduce this.

I think this is because we print to the terminal before reading all available characters on the stream. We should read and handle all typed characters before printing anything.
