### ISSUE TITLE
Usage in fish shell

### ISSUE THREAD

**Issue by gnapse** [thoughtbot/pick#46]
I've been struggling to use `pick` in the fish shell, which unfortunately has a bug when it comes to handling commands that block for input inside a command substitution (see fish-shell/fish-shell#1362).

There's a workaround though. For instance, instead of typing this command (which does not work properly in fish due to the aforementioned bug)

    rake (rake -T | cut -f2 -d' ' | pick)

We can instead type this:

    rake -T | cut -f2 -d' ' | pick | xargs rake

So I think it is more general that in the documentation this form of using `pick` might be preferred over the command substitution alternative, whenever possible.

However, there are some cases where this `xargs` workaround doesn't work. I've found just one, but there could be more:

    find . -type d | pick | xargs cd

The reason this does not work may have something to do with [this](http://stackoverflow.com/a/255415).

Any ideas of how to work around this problem with the `cd` command?

**Comment by calleerlandsson** [comment]
Hey @gnapse!

Thanks for reporting this.

I think all examples in the README and on the man page (except the `cd` one in the README) are using `xargs`. I'll keep this in mind when adding more examples, though.

As far as I know there is no way of working around the limitation of `cd` being a shell builtin and the current working directory being a property of the current process. When you run `xargs cd`, your shell will spawn a new `xargs` process that will in turn spawn a new shell process that changes into the directory before exiting. This will not affect the outer shell.

**Comment by gnapse** [comment]
Agreed. More than an actual bug, I thought it was important to raise attention to this issue. The bug, if any, if fish's fault in this case.

**Comment by xijo** [comment]
I found a workaround for this problem until fish-shell/fish-shell#1362 is solved

```fish
function scm -d 'Pick and jump into a subdirectory of ~/scm'
  set evalfn /tmp/pick_scm    # define a tmp file to store the pick result
  ls ~/scm | pick >$evalfn    # run pick and store the result
  eval cd ~/scm/(cat $evalfn) # read the content of the file and use it for the cd
  rm $evalfn                  # remove the tmp file afterwards
end
```

**Comment by grekko** [comment]
@xijo :heart: Thanks for the workaround! :)
