### ISSUE TITLE
ITP for debian

### ISSUE THREAD

**Issue by eavgerinos** [thoughtbot/pick#47]
I intend to package and maintain pick for Debian.

All files are licensed with the MIT license?

**Comment by calleerlandsson** [comment]
@eavgerinos That's great, thank you!

There is some BSD licensed code in https://github.com/thoughtbot/pick/tree/master/src/compat.

**Comment by eavgerinos** [comment]
Nice :) I'll close this issue when the ftp-masters approve the package.

**Comment by calleerlandsson** [comment]
Awesome! Thanks so much!

**Comment by eavgerinos** [comment]
UPDATE: Progress can be tracked [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=780483)

**Comment by eavgerinos** [comment]
Submitted the package to [Debian](https://ftp-master.debian.org/new/pick_1.1.1-1.html).

Now we are waiting the Debian ftp-masters to review it (it may take a while considering they are busy with the jessie stable release)

**Comment by calleerlandsson** [comment]
That's awesome! Thanks for helping out, @eavgerinos!

**Comment by eavgerinos** [comment]
Accepted to Debian unstable (at last) :)

**Comment by calleerlandsson** [comment]
Great! Thanks a lot @eavgerinos! Would you like to add installation instructions to the README?

**Comment by eavgerinos** [comment]
Will do later today :) (or worst case withing this week)

**Comment by calleerlandsson** [comment]
No hurry! Thanks.

**Comment by calleerlandsson** [comment]
Hey @eavgerinos! I just released pick 1.2.0. Would you like to update the Debian package and also add installation instructions to the README?
