### ISSUE TITLE
Abstract BSD specific code

### ISSUE THREAD

**Issue by Keithbsmiley** [thoughtbot/pick#6]
To compile pick locally on OS X I had to remove the `bsd` specific code. This is the diff:

```diff
diff --git i/src/Makefile.am w/src/Makefile.am
index 7709758..1b10f31 100644
--- i/src/Makefile.am
+++ w/src/Makefile.am
@@ -1,4 +1,4 @@
-AM_LDFLAGS=-lncurses -lbsd
+AM_LDFLAGS=-lncurses
 AM_CFLAGS=-Wall -Wextra -pedantic-errors -Wno-unused-parameter -Werror
 bin_PROGRAMS=pick
 dist_pick_SOURCES=choice.c choice.h choices.c choices.h io.c io.h main.c ui.c ui.h compat/queue.h
diff --git i/src/ui.c w/src/ui.c
index 23a765c..fea3ab9 100644
--- i/src/ui.c
+++ w/src/ui.c
@@ -7,7 +7,6 @@
 #include <stdlib.h>
 #include <string.h>
 #include <unistd.h>
-#include <bsd/string.h>
 
 #ifdef HAVE_FULL_QUEUE_H
 #include <sys/queue.h>
```

I haven't noticed any side effects of this but I'm sure this was in there for other platforms. Can we move this to somewhere it doesn't cause issue?

**Comment by calleerlandsson** [comment]
Although I still think we should merge #10 for enhanced portability, 59c434f1ecc78ccfd6ba53de37f7ef9b6387624a from #16 should be solving this issue. Could @teoljungberg or @Keithbsmiley try to build an run on OS X?

**Comment by teoljungberg** [comment]
Building from master, on my OS X machine, works great after the merge :+1:
I agree on merging #10 for even better portability
