### ISSUE TITLE
A note on sizeof

### ISSUE THREAD

**Issue by GBuella** [thoughtbot/pick#65]
Hi, just a little constructive note on some C code containing the expression sizeof(char)

Writing it is unnecessary, practically never used, and a bit confusing.

From ISO C11
6.5.3.4.4
"When sizeof is applied to an operand that has type char, unsigned char, or
signed char, (or a qualified version thereof) the result is 1"

By definition sizeof measures size in chars.

On the other hand,

line = calloc(sizeof(line[0]), line_length);

or

line = calloc(sizeof(*line), line_length);

make more sense than

line = calloc(sizeof(char), line_length);

**Comment by calleerlandsson** [comment]
These are really good points and I think the following makes a lot more sense since it would not require changing when the type of line is changed:

    line = calloc(sizeof(*line), line_length);

Lets keep this issue open until these instances have been replaced.

Thanks for the feedback, @GBuella!
