### ISSUE TITLE
install directions for "from source"

### ISSUE THREAD

**Issue by mooreniemi** [thoughtbot/pick#66]
on CentOS I needed to give an additional flag to `wget`

`wget --output-document=pick-1.1.1.tar.gz.asc https://github.com/thoughtbot/pick/releases/download/v1.1.1/pick-1.1.1.tar.gz.asc`
`wget --output-document=pick-1.1.1.tar.gz https://github.com/thoughtbot/pick/releases/download/v1.1.1/pick-1.1.1.tar.gz`

for those that want to just copy pasta what I did for the CentOS install, continue from the above:
`gpg --verify pick-1.1.1.tar.gz.asc`
`tar -xzf pick-1.1.1.tar.gz`
`cd pick-1.1.1`
`./configure`
`make`
`sudo make install`

**Comment by calleerlandsson** [comment]
Hey @mooreniemi,

What happened if you did not supply the --output-document flag? What version of wget are you running?

**Comment by calleerlandsson** [comment]
I'll close this issue due to inactivity.
