### ISSUE TITLE
pick -d splits by the first occurrence of IFS

### ISSUE THREAD

**Issue by temochka** [thoughtbot/pick#69]
The man page currently states the following:

> When the -d option is supplied, input lines will be split into two parts by the **last occurrence of IFS**.

However, the observed behavior is the opposite of that (split by the first occurrence):

```
$ pick -d <<< "foo bar baz qux"
foo
```

I’ll be happy to help modify `io_read_choices` to match the documented behavior, if you’d like to fix that in the code.

P.S. There is also a typo in word "occurrence" in this man page.

**Comment by calleerlandsson** [comment]
Hey @temochka, thanks for reporting this! This is definitely a bug and a PR would be much welcome!

**Comment by temochka** [comment]
Sounds good. I’ll try to work on it later this week!

**Comment by calleerlandsson** [comment]
Thanks!
