### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [thoughtbot/pick#72]
Would you like to add more error handling for return values from functions like the following?
- [printf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html "Print formatted output.") ⇒ [io_print_choice](https://github.com/thoughtbot/pick/blob/011075fb249f97fdee2df784eda54d0b857b45b3/src/io.c#L69)
- [strdup](http://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html "Duplicate a string.") ⇒ [choice_new](https://github.com/thoughtbot/pick/blob/4b89dd5b48d690d6424a2197a728e98badb3a5cf/src/choice.c#L9)

**Comment by calleerlandsson** [comment]
Thanks for finding those! If you'd want to help fix them, that'd be much appreciated. If not, I'll get to it as soon as I can!

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.

Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "AspectC++")?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](http://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?

**Comment by calleerlandsson** [comment]
Sure, checking return values makes a lot of sense.

I'm not sure what that would look like in terms of this project. Could you give me an example of how to apply it to pick?

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2FC.2B.2B "Tools for static code analysis") also for your software?

Do you find information sources like the following useful?
* Article "[A Reusable Aspect for Memory Allocation Checking](http://aspectc.net/ac_tutorial.html#reusablemachecking "AspectC Tutorial")"
* Document "[Aspect-Oriented Software Development - An Introduction](http://www.info.ucl.ac.be/~jbrichau/courses/introductionToAOSD.pdf "AOSD")" by Johan Brichau and Theo D'Hondt
* Paper "[On Typesafe Aspect Implementations in C++](http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.125.2164 "AspectC++")" by Daniel Lohmann and Olaf Spinczyk

**Comment by calleerlandsson** [comment]
Static analysis seems like a good idea. Which program would you recommend?

Thanks for the links. The second one seems to be broken.

In general I feel like I have a tough time imagining what this would look like in C. Would it rely heavily on macros? The articles you link to seem to be for a specialized aspect oriented language and C++ respectively.

**Comment by elfring** [comment]
I suggest to reuse the following tools for finding more update candidates depending on your preferences for factors like [freedom](https://www.fsf.org/about/what-is-free-software "Choosing freedom"), [licence costs](http://www.computerweekly.com/feature/Lower-your-software-licence-fees "Lower your software licence fees") and programming language support.
1. [AspectC++](http://aspectc.org/ "Aspect-oriented software development")
2. [Secure Programming Lint](http://splint.org/faq.html#quest9 "Which compilers does Splint support?")
3. [Coccinelle](http://coccinelle.lip6.fr/ "Source code transformation engine")
4. [Coverity Scan](https://scan.coverity.com/ "Static source code analysis")


>The second one seems to be broken.

Do you get further ideas from another information source like [the "Wiley Encyclopedia of Computer Science and Engineering"](http://onlinelibrary.wiley.com/doi/10.1002/9780470050118.ecse022/abstract "Aspect-Oriented Software Development: an Introduction")?


>Would it rely heavily on macros?

How do you think about to delegate specific software maintenance tasks to dedicated development tools?

**Comment by akerl** [comment]
This is the weirdest github issue bot I've seen in a while

**Comment by calleerlandsson** [comment]
I'm not sure how to handle this issue. PRs to improve code quality are much welcome.

**Comment by elfring** [comment]
How do you think about to integrate any of the suggested tools into your software development process?

**Comment by calleerlandsson** [comment]
If you submit a PR integrating it, I'd be happy to consider it!

**Comment by elfring** [comment]
I would appreciate if a bit more consensus can be achieved before further efforts will be invested for possible changes.
Would you like to integrate the tool "AspectC++" into your software build system?

**Comment by calleerlandsson** [comment]
I'm not sure how that integration would affect the project. Since AspectC++ seems to be a totally different language from C, I think it would require a total rewrite. If so, I'd not want to integrate it. If not, could you please demonstrate what kind of things would have to change by supplying an example?

**Comment by elfring** [comment]
A tool like "AspectC++" is providing another programming language which supports to specify the combination of a pointcut with advice. (Such a C++ tool can also support the programming language "C" to some degree.)
Would you like to reuse such functionality generally?

**Comment by calleerlandsson** [comment]
OK, I'm not interested in doing a rewrite in AspectC++.
