### ISSUE TITLE
Broken in ncurses 6

### ISSUE THREAD

**Issue by rosshadden** [thoughtbot/pick#73]
`pick` does not work with `ncurses` after its update to version 6.  I have version 6.0-3 installed, but I'm guessing 6.x has the issue.  The other ncurses apps I have tried work fine after the update.

![image](https://cloud.githubusercontent.com/assets/669012/10063633/223f9ae0-623e-11e5-82f1-f57722e3f8fb.png)

**Comment by calleerlandsson** [comment]
Thanks for reporting this @rosshadden. I'm not sure what might be causing this and will look into it when I have time.

**Comment by rosshadden** [comment]
Here's what is going on. In Arch Linux, they updated to `ncurses` 6, as implied by my above post.  This means it's a breaking change for things explicitly looking for `/usr/lib/libncursesw.so.5`.

I "solved" this by installing an `ncurses5` package alongside my main `ncurses` package, however the best solution would be for `pick` to instead use `/usr/lib/libncursesw.so`.  On most systems this should be a symlink to the current `ncurses`, in my case `6`.  I don't see in the code where this reference is made, so I don't know where to change it.  You guys are possibly using a library or wrapper around `ncurses` which is doing this.  If so let me know and I will open an issue there.

Thanks!

**Comment by calleerlandsson** [comment]
Interesting.

All the linking is done by autotools and the libraries to link to are specified in [configure.ac](https://github.com/thoughtbot/pick/blob/011075fb249f97fdee2df784eda54d0b857b45b3/configure.ac). I don't see how this would lock it at version 5, though.

If you uninstall `ncurses5` and `pick`, then reinstall `pick` without installing `ncurses5`, will it work?

**Comment by rosshadden** [comment]
Yes, that works!  Thanks!
