### ISSUE TITLE
Selection line (white background) doesn't show in tmux

### ISSUE THREAD

**Issue by FreedomBen** [thoughtbot/pick#78]
when running pick inside tmux, the white background that shows the current selection (which can be advanced with Ctrl+N) cannot be seen.  The selection does change, but the white background is not visible.  Works fine when not inside a tmux session.  Am I missing a configuration setting or something?

System: Fedora 22 x64

**Comment by calleerlandsson** [comment]
Hey @FreedomBen, thanks for reporting this.

What versions of pick and tmux are you running? Might this be an issue with your colorscheme similar to #44?

**Comment by FreedomBen** [comment]
Tmux version:  1.9a-5
Pick version:  1.1.1 and 1.2.1 with same effect

This could very well be #44.  I'll give that a try and report back.  Thanks!

**Comment by FreedomBen** [comment]
Yep it's definitely #44.  Thanks for referring.  I did some searching through open/closed issues before opening one but missed that one.

Some great instructions here:  http://unix.stackexchange.com/questions/167843/tmux-vim-colorscheme-background-is-not-showing

My solution was to put this in `~/.bashrc` :

    # hack to fix tmux color scheme not showing background standout color
    export TERM="xterm-256color"

Might have side effects but at least pick is working again.  Thanks!

**Comment by calleerlandsson** [comment]
I'm happy the problem is solved. Thanks for documenting how you did it, @FreedomBen!
