### ISSUE TITLE
Exiting from the command line messes up the terminal

### ISSUE THREAD

**Issue by Keithbsmiley** [thoughtbot/pick#9]
Related to other onscreen issues, when you run pick from the command line. For example:

```bash
git ls-files | pick
```

And exit, either successfully or not, this happens:

![screen shot 2014-11-25 at 9 19 13 pm](https://cloud.githubusercontent.com/assets/283886/5196614/dcbe32ee-74e8-11e4-9797-285a5902310e.png)

**Comment by calleerlandsson** [comment]
This is solved in 769b3b5335e7cbdef4de1a8c29242ac405cbebfa, which also reopens #4.
